### ISSUE TITLE
FEATURE REQUEST: Support use of same device for curtailment and augmentation

### ISSUE THREAD

**Issue by davidraker** [VOLTTRON/volttron-GS#2]
Currently, a device is available for augmentation when it is not available for curtailment. This is not universally true:
- A VAV which is 50% open should be available for both augmentation and curtailment. 
- If the AHU is in unoccupied mode, the device might not have airflow, and thus will be unavailable to either mode.

Please add support to ILC for separate definitions of augment and curtail condition in the control configuration.

**Comment by rlutes** [comment]
Resolved with commit 11c220094f514e5e1b791f4548fad771d11f9073.
