### ISSUE TITLE
Create documentation for all applications

### ISSUE THREAD

**Issue by shwethanidd** [VOLTTRON/volttron-GS#7]
README for each application needs to be created describing the purpose and usage.

**Comment by nitin-barthwal** [comment]
Requesting update on Documentation. 
Please provide required manuals.

**Comment by shwethanidd** [comment]
@nitin-barthwal Please look at https://github.com/VOLTTRON/volttron-pnnl-applications. If there are any issues with documentation please raise a git issue in that repo.
volttron-GS will be deprecated soon.

Thanks!
